import os
import requests
from dotenv import load_dotenv

load_dotenv()

_token = os.getenv("GITLAB_TOKEN", "")
_project_id = os.getenv("GITLAB_PROJECT_ID", "")
_gitlab_url = os.getenv("GITLAB_URL", "https://gitlab.com")
_use_real = bool(_token and _project_id and not _token.startswith("glpat-..."))

_headers = {"PRIVATE-TOKEN": _token, "Content-Type": "application/json"}
_api = f"{_gitlab_url}/api/v4/projects/{_project_id}"


def create_branch(branch_name: str):
    if _use_real:
        resp = requests.post(f"{_api}/repository/branches",
                             headers=_headers,
                             json={"branch": branch_name, "ref": "main"})
        resp.raise_for_status()
        print(f"   [GitLab] Branch created: {branch_name}")
    else:
        print(f"   [Mock GitLab] Branch created: {branch_name}")


def commit_fix(branch_name: str, fix: dict, session_id: str):
    if _use_real:
        file_path = fix.get("file_path", "agitic_fix.txt")
        content = fix.get("code_after", "# fix generated by Agitic")
        resp = requests.post(f"{_api}/repository/files/{requests.utils.quote(file_path, safe='')}",
                             headers=_headers,
                             json={
                                 "branch": branch_name,
                                 "content": content,
                                 "commit_message": f"fix: {fix.get('fix_description', 'Agitic auto-fix')} [session:{session_id}]",
                                 "encoding": "text",
                             })
        if resp.status_code == 400:
            # File exists — update instead
            resp = requests.put(f"{_api}/repository/files/{requests.utils.quote(file_path, safe='')}",
                                headers=_headers,
                                json={
                                    "branch": branch_name,
                                    "content": content,
                                    "commit_message": f"fix: {fix.get('fix_description', 'Agitic auto-fix')} [session:{session_id}]",
                                })
        resp.raise_for_status()
        print(f"   [GitLab] Fix committed to {branch_name}")
    else:
        print(f"   [Mock GitLab] Fix committed to {branch_name}: {fix.get('fix_description', '')}")


def create_merge_request(branch_name: str, analysis: dict, security_report: dict, attempts: list, ci_passed: bool) -> str:
    if _use_real:
        attempt_rows = "\n".join(
            f"| {a['attempt']} | {'PASS' if a['passed'] else 'FAIL'} | {a['validation'].get('confidence','—')} | {a['validation'].get('verdict','—')} |"
            for a in attempts
        )
        description = f"""## Agitic Auto-Fix

**Error:** `{analysis.get('error_type', 'Unknown')}`
**Severity:** {analysis.get('severity', '—')}
**Root Cause:** {analysis.get('root_cause', '—')}
**Confidence:** {analysis.get('confidence', '—')}

---

### Security Report
- Score: {security_report.get('security_score', '?')}/100
- Risk: {security_report.get('risk_level', '—')}
- Summary: {security_report.get('summary', '—')}

---

### Retry Timeline
| Attempt | Result | Confidence | Verdict |
|---------|--------|------------|---------|
{attempt_rows}

---
*Generated by [Agitic](https://gitlab.com) — autonomous CI/CD fix agent*"""

        resp = requests.post(f"{_api}/merge_requests",
                             headers=_headers,
                             json={
                                 "source_branch": branch_name,
                                 "target_branch": "main",
                                 "title": f"fix: {analysis.get('error_type', 'Auto-fix')} (Agitic)",
                                 "description": description,
                                 "remove_source_branch": True,
                             })
        resp.raise_for_status()
        mr_url = resp.json().get("web_url", "")
        print(f"   [GitLab] MR opened: {mr_url}")
        return mr_url
    else:
        mr_id = abs(hash(branch_name)) % 1000
        mr_url = f"https://gitlab.com/demo/agitic/-/merge_requests/{mr_id}"
        print(f"   [Mock GitLab] MR opened: {mr_url}")
        return mr_url
